@startuml
class BaseEventType  {
BrowseName: BaseEventType
IsAbstract: True
EventId: ByteString
EventType: NodeId
SourceNode: NodeId
SourceName: String
Time: UtcTime
ReceiveTime: UtcTime
LocalTime: TimeZoneDataType
Message: LocalizedText
Severity: UInt16
}

class AuditEventType {
BrowseName: AuditEventType
IsAbstract: Boolean
ActionTimeStamp: UtcTime
Status: Boolean
ServerId: String
ClientAuditEntryId: String
ClientUserId: String
}

class AuditSecurityEventType{
BrowseName: AuditSecurityEventType
IsAbstract: Boolean
StatusCodeId: StatusCode
}

class AuditChannelEventType{
BrowseName: AuditChannelEventType
IsAbstract: Booolean
SecureChannelId: String
}
class AuditOpenSecureChannelEventType{
BrowseName: AuditOpenSecureChannelEventType
IsAbstract: Boolean
ClientCertificate: ByteString
ClientCertificateThumbprint: String
RequestType: SecurityTokenRequestType
SecurityPolicyUri: String
SecurityMode: MessageSecurityMode
RequestedLifetime:Duration
}
class AuditOpenSecureChannelEventType{
BrowseName: AuditOpenSecureChannelEventType
IsAbstract: Boolean
ClientCertificate: ByteString
ClientCertificateThumbprint: String
RequestType: SecurityTokenRequestType
SecurityPolicyUri: String
SecurityMode: MessageSecurityMode
RequestedLifetime: Duration
}



class AuditSessionEventType{
BrowseName: AuditSessionEventType
IsAbstract: Boolean
SessionId: NodeId
}
class AuditCreateSessionEventType{
BrowseName: AuditCreateSessionEventType
IsAbstract: Boolean
SecureChannelId: String
ClientCertificate: ByteString
ClientCertificateThumbprint: String
RevisedSessionTimeout: Duration
}
class AuditUrlMismatchEventType{
BrowseName: AuditUrlMismatchEventType
IsAbstract: Boolean
EndpointUrl:String
}
class AuditActivateSessionEventType{
BrowseName: AuditActivateSessionEventType
IsAbstract: Boolean
ClientSoftwareCertificates: SignedSoftwareCertificate[]
UserIdentityToken: UserIdentityToken
SecureChannelId: String
}
class AuditCancelEventType{
BrowseName: AuditCancelEventType
IsAbstract: Boolean
RequestHandle: UInt32
}

class AuditCertificateEventType{
BrowseName: AuditCertificateEventType
IsAbstract: Boolean
Certificate: ByteString
}
class AuditCertificateDataMismatchEventType{
BrowseName: AuditCertificateDataMismatchEventType
IsAbstract: Boolean
InvalidHostname: String
InvalidUri: String
}
class AuditCertificateExpiredEventType{
BrowseName: AuditCertificateExpiredEventType
IsAbstract: Boolean
}
class AuditCertificateInvalidEventType{
BrowseName: AuditCertificateInvalidEventType
IsAbstract: Boolean
}
class AuditCertificateUntrustedEventType{
BrowseName: AuditCertificateUntrustedEventType
IsAbstract: Boolean
}
class AuditCertificateRevokedEventType{
BrowseName: AuditCertificateRevokedEventType
IsAbstract: Boolean
}
class AuditCertificateMismatchEventType{
BrowseName: AuditCertificateMismatchEventType
IsAbstract: Boolean
}

class AuditNodeManagementEventType{

}
class AuditUpdateEventType{

}
class AuditUpdateMethodEventType{

}

class SystemEventType {
BrowseName: SystemEventType
IsAbstract: Boolean
}

class BaseModelChangeEventType {
BrowseName: BaseModelChangeEventType
IsAbstract: boolean
}

class SemanticChangeEventType{
BrowseName: SemanticChangeEventType
IsAbstract: Boolean
Changes: SemanticChangeStructureDataType[]
}

class EventQueueOverflowEventType{
BrowseName: EventQueueOverflowEventType
IsAbstract: Boolean
}

class ProgressEventType{
BrowseName: ProgressEventType
IsAbstract: boolean
Context: BaseDataType
Progress: UInt16
}




BaseEventType <|--  AuditEventType
BaseEventType <|--  SystemEventType
BaseEventType <|--  BaseModelChangeEventType
BaseEventType <|--  SemanticChangeEventType
BaseEventType <|--  EventQueueOverflowEventType
BaseEventType <|--  ProgressEventType

AuditEventType <|-- AuditSecurityEventType
AuditEventType <|-- AuditNodeManagementEventType
AuditEventType <|-- AuditUpdateEventType
AuditEventType <|-- AuditUpdateMethodEventType

AuditSecurityEventType <|-- AuditChannelEventType
AuditSecurityEventType <|-- AuditSessionEventType
AuditSecurityEventType <|-- AuditCertificateEventType

AuditChannelEventType <|-- AuditOpenSecureChannelEventType

AuditSessionEventType <|-- AuditCreateSessionEventType
AuditSessionEventType <|-- AuditActivateSessionEventType
AuditSessionEventType <|-- AuditCancelEventType


AuditCreateSessionEventType <|-- AuditUrlMismatchEventType

AuditCertificateEventType <|-- AuditCertificateDataMismatchEventType
AuditCertificateEventType <|-- AuditCertificateExpiredEventType
AuditCertificateEventType <|-- AuditCertificateInvalidEventType
AuditCertificateEventType <|-- AuditCertificateUntrustedEventType
AuditCertificateEventType <|-- AuditCertificateRevokedEventType
AuditCertificateEventType <|-- AuditCertificateMismatchEventType



@enduml